# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Peter Maidens
tagline:          My personal website
description:      Father, maker, and software developer extraordinaire!
url:              http://www.petermaidens.com

author:
  name:           'Peter Maidens'
  url:            http://www.petermaidens.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pmaidens/pmaidens.github.io
